interface Features {
  title: string;
  amount: boolean | string | number;
  description?: string;
}

interface Price {
  popular: boolean,
  packageName: string,
  users: number | string,
  price: {
    monthly: string,
    yearly: string
  },
  userPrice?: {
    monthly: number,
    yearly: number
  },
  subtitle: string,
  btn: string,
  purchaseLink: string,
  top: Array<Features>,
  features: {
    functions: Array<Features>,
    integrations: Array<Features>,
    customizing: Array<Features>,
    support: Array<Features>,
  },
}

export const prices: Array<Price> = [
  {
    popular: false,
    packageName: 'Free',
    users: 1,
    price: { monthly: '0', yearly: '0' },
    subtitle: 'Features',
    btn: 'Start Free',
    purchaseLink: 'https://my.orbnet.de/account/register/',
    top: [
      { title: 'Benutzer', amount: 1 },
      { title: 'Rechnungen schreiben', amount: 5 },
      { title: 'Angebote schreiben', amount: true },
    ],
    features: {
      functions: [
        { title: 'Benutzer', amount: 1 },
        { title: 'Rechnungen schreiben', amount: 5 },
        { title: 'Angebote schreiben', amount: true },
        { title: 'Mahnungen (Manuell)', amount: true },
        { title: 'Gutschriften', amount: true },
        { title: 'Kundenverwaltung', amount: true },
        { title: 'Produkte & Dienstleistungen', amount: true },
        { title: 'Notifications & Reminder', amount: true },
        { title: 'Zeiterfassung & Reports', amount: true },
        { title: 'Online-Banking', amount: false },
        { title: 'Wiederkehrende Rechnungen', amount: false },
        { title: 'Projektmanagement', amount: false },
        { title: 'Mahnungen (Automatisiert)', amount: false },
        { title: 'Steuerberater Login', amount: false },
        { title: 'Events', amount: 1 },
        { title: 'Dokumentenverwaltung', amount: false },
        { title: 'OCR-Erkennung', amount: false },
        { title: 'Landingpage-Generator', amount: false },
        { title: 'Synchronisierung Kalender auf Endgeräte', amount: false },
        { title: 'Benutzer-Management', amount: false },
      ],
      integrations: [
        { title: 'Google Kalender', amount: false },
        { title: 'Apple Kalender', amount: false },
        { title: 'Office365 Kalender', amount: false },
        { title: 'CalDAV Kalender', amount: false },
        { title: 'PayPal', amount: false },
        { title: 'Stripe', amount: false },
        { title: 'Kreditkarte', amount: false },
        { title: 'SEPA', amount: false },
        { title: 'Kauf auf Rechnung', amount: false },
        { title: 'Zoom', amount: false },
        { title: 'Microsoft Teams', amount: false },
        { title: 'Google Analytics', amount: false },
        { title: 'Facebook Pixel', amount: false },
        { title: 'DATEV Format Export', amount: false },
      ],
      customizing: [
        { title: 'orbnet Branding entfernen', amount: false },
        { title: 'Individuelle Farbgestaltung für Termine', amount: false },
        { title: 'Eigene Firmen-URL', amount: false, description: 'z.B.: orbnet.de/p/meinefirma' },
        { title: 'Event-Übersichtsseite', amount: false, description: 'Landingpage mit allen Angeboten' },
        { title: 'Custom Links für Events', amount: false, description: 'z.B.: orbnet.de/p/meinefirma/30min' },
        { title: 'Passwortschutz auf Events', amount: false },
      ],
      support: [
        { title: 'Support-Ticket', amount: true },
        { title: 'E-Mail Support', amount: false },
      ],
    },
  },
  {
    popular: true,
    packageName: 'Pro',
    users: '1-2',
    price: { monthly: '15', yearly: '12' },
    userPrice: { monthly: 10, yearly: 8 },
    subtitle: 'Features',
    btn: 'Start Pro',
    purchaseLink: 'https://my.orbnet.de/account/register/',
    top: [
      { title: 'Benutzer', amount: '1-2' },
      { title: 'Rechnungen schreiben', amount: true },
      { title: 'Angebote schreiben', amount: true },
    ],
    features: {
      functions: [
        { title: 'Benutzer', amount: '1-2' },
        { title: 'Rechnungen schreiben', amount: true },
        { title: 'Angebote schreiben', amount: true },
        { title: 'Mahnungen (Manuell)', amount: true },
        { title: 'Gutschriften', amount: true },
        { title: 'Kundenverwaltung', amount: true },
        { title: 'Produkte & Dienstleistungen', amount: true },
        { title: 'Notifications & Reminder', amount: true },
        { title: 'Zeiterfassung & Reports', amount: true },
        { title: 'Online-Banking', amount: true },
        { title: 'Wiederkehrende Rechnungen', amount: true },
        { title: 'Projektmanagement', amount: true },
        { title: 'Mahnungen (Automatisiert)', amount: true },
        { title: 'Steuerberater Login', amount: true },
        { title: 'Events', amount: true },
        { title: 'Dokumentenverwaltung', amount: true },
        { title: 'OCR-Erkennung', amount: true },
        { title: 'Landingpage-Generator', amount: true },
        { title: 'Synchronisierung Kalender auf Endgeräte', amount: true },
        { title: 'Usermanagement', amount: false },
      ],
      integrations: [
        { title: 'Google Kalender', amount: true },
        { title: 'Apple Kalender', amount: true },
        { title: 'Office365 Kalender', amount: true },
        { title: 'CalDAV Kalender', amount: true },
        { title: 'PayPal', amount: true },
        { title: 'Stripe', amount: true },
        { title: 'Kreditkarte', amount: true },
        { title: 'SEPA', amount: true },
        { title: 'Kauf auf Rechnung', amount: true },
        { title: 'Zoom', amount: true },
        { title: 'Microsoft Teams', amount: true },
        { title: 'Google Analytics', amount: true },
        { title: 'Facebook Pixel', amount: true },
        { title: 'DATEV Format Export', amount: true },
      ],
      customizing: [
        { title: 'orbnet Branding entfernen', amount: true },
        { title: 'Individuelle Farbgestaltung für Termine', amount: true },
        { title: 'Eigene Firmen-URL (orbnet.de/meinefirma)', amount: true },
        { title: 'Event-Übersichtsseite (Landingpage mit allen Angeboten)', amount: true },
        { title: 'Custom Links für Events (orbnet.de/meinefirme/30min)', amount: true },
        { title: 'Passwortschutz auf Events', amount: true },
      ],
      support: [
        { title: 'Support-Ticket', amount: true },
        { title: 'E-Mail Support', amount: true },
      ],
    },
  },
  {
    popular: false,
    packageName: 'Team',
    users: '3+',
    price: { monthly: '35', yearly: '28' },
    userPrice: { monthly: 5, yearly: 4 },
    subtitle: 'Features',
    btn: 'Start Team',
    purchaseLink: 'https://my.orbnet.de/account/register/',
    top: [
      { title: 'Benutzer', amount: '3+' },
      { title: 'Rechnungen schreiben', amount: true },
      { title: 'Angebote schreiben', amount: true },
    ],
    features: {
      functions: [
        { title: 'Benutzer', amount: '3+' },
        { title: 'Rechnungen schreiben', amount: true },
        { title: 'Angebote schreiben', amount: true },
        { title: 'Mahnungen (Manuell)', amount: true },
        { title: 'Gutschriften', amount: true },
        { title: 'Kundenverwaltung', amount: true },
        { title: 'Produkte & Dienstleistungen', amount: true },
        { title: 'Notifications & Reminder', amount: true },
        { title: 'Zeiterfassung & Reports', amount: true },
        { title: 'Online-Banking', amount: true },
        { title: 'Wiederkehrende Rechnungen', amount: true },
        { title: 'Projektmanagement', amount: true },
        { title: 'Mahnungen (Automatisiert)', amount: true },
        { title: 'Steuerberater Login', amount: true },
        { title: 'Events', amount: true },
        { title: 'Dokumentenverwaltung', amount: true },
        { title: 'OCR-Erkennung', amount: true },
        { title: 'Landingpage-Generator', amount: true },
        { title: 'Synchronisierung Kalender auf Endgeräte', amount: true },
        { title: 'Usermanagement', amount: true },
      ],
      integrations: [
        { title: 'Google Kalender', amount: true },
        { title: 'Apple Kalender', amount: true },
        { title: 'Office365 Kalender', amount: true },
        { title: 'CalDAV Kalender', amount: true },
        { title: 'PayPal', amount: true },
        { title: 'Stripe', amount: true },
        { title: 'Kreditkarte', amount: true },
        { title: 'SEPA', amount: true },
        { title: 'Kauf auf Rechnung', amount: true },
        { title: 'Zoom', amount: true },
        { title: 'Microsoft Teams', amount: true },
        { title: 'Google Analytics', amount: true },
        { title: 'Facebook Pixel', amount: true },
        { title: 'DATEV Format Export', amount: true },
      ],
      customizing: [
        { title: 'orbnet Branding entfernen', amount: true },
        { title: 'Individuelle Farbgestaltung für Termine', amount: true },
        { title: 'Eigene Firmen-URL (orbnet.de/meinefirma)', amount: true },
        { title: 'Event-Übersichtsseite (Landingpage mit allen Angeboten)', amount: true },
        { title: 'Custom Links für Events (orbnet.de/meinefirme/30min)', amount: true },
        { title: 'Passwortschutz auf Events', amount: true },
      ],
      support: [
        { title: 'Support-Ticket', amount: true },
        { title: 'E-Mail Support', amount: true },
      ],
    },
  },
];
